{"cf_action": null, YES
"cf_subquery": null, Not in zoho
"cf_warranty_status698243": null,
"cf_field_status": null,
"cf_service": null,
"cf_status": null,
"cf_serial_number995088": null,
"cf_invoiceorder_number": null,
"cf_pending": null,
"cf_resolution_code": null,
"cf_issue_type": null,
"cf_issue_date": null,
"cf_courier_partner": null,
"cf_state": null,
"cf_complaint_type_logistics": null,
"cf_pincode": YES, 
"cf_invoiceorder_no": null,
"cf_purchased_on": null,
"cf_warranty_status": null,
"cf_category": null,
"cf_subcategory": null,
"cf_model": null,
"cf_pending_on": null,
"cf_sub_code": null,
"cf_action896199": null,
"cf_level1": null,
"cf_level2": null,
"cf_fsm_contact_name": null,
"cf_serviceability": null,
"cf_reason": null,
"cf_fsm_phone_number": null,
"cf_fsm_service_location": null,
"cf_fsm_appointment_start_time": null,
"cf_awbtracking_number": null,
"cf_fsm_appointment_end_time": null,
"cf_create_service_task": false,
"cf_split_ticket": false
}