{
        "cf_action_to_be_taken": "No action", YES
        "cf_state_1": null,
        "cf_origin": null,
        "cf_order_number": null,
        "cf_closure_code": null,
        "cf_purchased_on": YES,
        "cf_city": "KANPUR",
        "cf_delivered": null,
        "cf_ticket_age": null,
        "cf_due_date_marketing": null,
        "cf_reason_code": null,
        "cf_courier_partner": YES,
        "cf_pending_warehouse": "No",
        "cf_customer_issue": null,
        "cf_product_category": null,
        "cf_catalogue": null,
        "cf_owner": null,
        "cf_pin_code":YES,
        "cf_call_status_1": null,
        "cf_product_model_number": YES,
        "cf_issue_date": YES,
        "cf_type_of_issue": null,
        "cf_spares_sent": null,
        "cf_issue_type": YES,
        "cf_address_line_1": "127/1086 , W-1, Saket Nagar",
        "cf_task": null,
        "cf_awb_number": YES,
        "cf_address_line_2": null,
        "cf_pending_on": YES,
        "cf_model": YES,
        "cf_images": null,
        "cf_expected_delivery": null,
        "cf_product_serial_number": "LLM180",
        "cf_invoice_number": null
}