const OPTIONS = {
	zoho: {
		scope: 'Desk.tickets.ALL,Desk.contacts.READ,Desk.contacts.WRITE,Desk.contacts.UPDATE,Desk.contacts.CREATE,Desk.settings.ALL,Desk.basic.CREATE,Desk.basic.READ,Desk.search.READ',
		API1: 'https://desk.zoho.com/api/v1/',
		ACCOUNT_API: 'https://accounts.zoho.com/oauth/v2/token',
		REDIRECT_URL: () => {
			if (process.env.ENVIRONMENT === 'development') {
				return '';
			}
			return '';
		},
		GRANT_TYPE_AUTH: 'authorization_code',
		GRANT_TYPE_REFRESH: 'refresh_token',
	},
	freshDesk: {
		scope: 'Desk.tickets.ALL,Desk.contacts.READ,Desk.contacts.WRITE,Desk.contacts.UPDATE,Desk.contacts.CREATE,Desk.settings.ALL,Desk.basic.CREATE,Desk.basic.READ,Desk.search.READ',
		API: 'https://lifelongonline.freshdesk.com/api/v2/',
	},

	modelsList: [
		{ modelNumber: 'Models', category: 'Category', subCategory: 'Sub Category' },
		{ modelNumber: 'LLMG45', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLF108', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLMG02', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG01', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG03', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG20', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG73', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG72', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG91', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG100', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG111', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG21', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'OTG10L', category: 'Kitchen', subCategory: 'OTG' },
		{ modelNumber: 'OTG16L', category: 'Kitchen', subCategory: 'OTG' },
		{ modelNumber: 'OTG26L', category: 'Kitchen', subCategory: 'OTG' },
		{ modelNumber: 'OTG28L', category: 'Kitchen', subCategory: 'OTG' },
		{ modelNumber: 'LLSM114G', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLSM114T', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLSM115G', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLSM115T', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLSM116G', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLSM116T', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLWM105', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLPM900', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLPM1000', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'EK02', category: 'Kitchen', subCategory: 'KETTLE' },
		{ modelNumber: 'EK01', category: 'Kitchen', subCategory: 'KETTLE' },
		{ modelNumber: 'LLHB02', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLPT09', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'LLGS09', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS36', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS27', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS18', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLTM09', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM18', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM27', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM36', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM45', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLCK18', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCK16', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLFP04', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLTW08', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLKA02', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLSFPR01B', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF07', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF08', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLVC18', category: 'Home Appliances', subCategory: 'Vacuum Cleaner' },
		{ modelNumber: 'LLGS01', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'WH01', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLM108', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM09', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM27', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM45', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM54', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{
			modelNumber: 'LLM72',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM81',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM90',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM99',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM18',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{ modelNumber: 'LLM63', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{
			modelNumber: 'LLM126',
			category: 'Health & Personal Care',
			subCategory: 'Other Massagers',
		},
		{ modelNumber: 'LLM36', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM117', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM180', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM171', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLTM207', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLM162', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM207', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM549', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLM216', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{
			modelNumber: 'LLM720',
			category: 'Health & Personal Care',
			subCategory: 'Other Massagers',
		},
		{
			modelNumber: 'LLM153',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM909',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM135',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM144',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{ modelNumber: 'LLM225', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLHA36', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLHA54', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLHA45', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLHA09', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCK27', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLGS118', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS45', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS99', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS23', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLCKR24', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR18', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR12', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR06', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR48', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR72', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR66', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR30', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR84', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR78', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCF118', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF112', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF106', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF18', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF09', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLIC12', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLDI09', category: 'Home Appliances', subCategory: 'Dry Iron' },
		{ modelNumber: 'LLMG78', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG70', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG66', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG109', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG79', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG74', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLCMB03', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB02', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLWH106', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLJAR_LARGE', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLJAR_SMALL', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLJAR_MEDIUM', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLGS108', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLHA18', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLHA27', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLGS44', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLPCM005', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLIC20', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLMG10', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLPCM11', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCM007', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCM13', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLM063', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLPCM09', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'TR11', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCW10', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW24', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW20', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLCMB01', category: 'Home Appliances', subCategory: 'Combo' },
		{
			modelNumber: 'LLM621',
			category: 'Health & Personal Care',
			subCategory: 'Other Massagers',
		},
		{ modelNumber: 'LLHB01S', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{
			modelNumber: 'LLM234',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{ modelNumber: 'LLPCW04', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW16', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW14', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW02', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW08', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW06', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW18', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW12', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCW28', category: 'Lifestyle', subCategory: 'Female Grooming' },
		{ modelNumber: 'LLPCW26', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLPCM07', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCM05', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCM03', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLEB01', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLWH104', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLEC01', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLHB04', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLHB03', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLTM99', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLM243', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLMC01', category: 'Kitchen', subCategory: 'Pressure Cooker' },
		{ modelNumber: 'LLATWM09', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLATWM08', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLATWM07', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLSBSR525', category: 'Home Appliances', subCategory: 'REFRIGERATOR' },
		{ modelNumber: 'LLAWMD05', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLTM81', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLFH01', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLWH25', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLWH15', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLF72', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF63', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF54', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF45', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF36', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF27', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF18', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF09', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLES02', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'HB02-P', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'HB01-SS', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'SM112G', category: 'Kitchen', subCategory: 'Sandwich Maker' },
		{ modelNumber: 'SM112T', category: 'Kitchen', subCategory: 'Sandwich Maker' },
		{ modelNumber: 'SM114G', category: 'Kitchen', subCategory: 'Sandwich Maker' },
		{ modelNumber: 'SM114T', category: 'Kitchen', subCategory: 'Sandwich Maker' },
		{ modelNumber: 'SM116G', category: 'Kitchen', subCategory: 'Sandwich Maker' },
		{ modelNumber: 'SM116T', category: 'Kitchen', subCategory: 'Sandwich Maker' },
		{ modelNumber: 'LLSM118G', category: 'Kitchen', subCategory: 'SANDWICH MAKER' },
		{ modelNumber: 'BT02', category: 'Lifestyle', subCategory: 'Female Grooming' },
		{ modelNumber: 'EP01', category: 'Lifestyle', subCategory: 'Female Grooming' },
		{ modelNumber: 'LLPCM01', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCM25', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLM027', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLWH09', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLWM01', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLWM02', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLOT16', category: 'Kitchen', subCategory: 'OTG' },
		{ modelNumber: 'LLRC18', category: 'Kitchen', subCategory: 'Pressure Cooker' },
		{ modelNumber: 'LLRC01', category: 'Kitchen', subCategory: 'Pressure Cooker' },
		{ modelNumber: 'HSB01', category: 'Lifestyle', subCategory: 'Female Grooming' },
		{ modelNumber: 'LLCF31', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF10', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{
			modelNumber: 'LLVST300',
			category: 'Home Appliances',
			subCategory: 'Voltage Stabilizers',
		},
		{ modelNumber: 'LLCF21', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{
			modelNumber: 'LLVST200',
			category: 'Home Appliances',
			subCategory: 'Voltage Stabilizers',
		},
		{
			modelNumber: 'LLVST100',
			category: 'Home Appliances',
			subCategory: 'Voltage Stabilizers',
		},
		{ modelNumber: 'HS03', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLCKR113', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR112', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR111', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR114', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR124', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR123', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR122', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR121', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR102', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR101', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLSL01', category: 'SPORTS', subCategory: 'EXERCISE' },
		{ modelNumber: 'LLSR01', category: 'SPORTS', subCategory: 'EXERCISE' },
		{ modelNumber: 'LLCMB06', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLSP16A', category: 'Smart Home', subCategory: 'SMART PLUG' },
		{ modelNumber: 'LLSP10A', category: 'Smart Home', subCategory: 'SMART PLUG' },
		{ modelNumber: 'LLSB9W', category: 'Smart Home', subCategory: 'SMART BULB' },
		{ modelNumber: 'LLSB12W', category: 'Smart Home', subCategory: 'SMART BULB' },
		{ modelNumber: 'LLVC15', category: 'Home Appliances', subCategory: 'Vacuum Cleaner' },
		{ modelNumber: 'LLVC10', category: 'Home Appliances', subCategory: 'Vacuum Cleaner' },
		{ modelNumber: 'LLMG750', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLM261', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLMG320', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG310', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG300', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG220', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG210', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLMG200', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLHB20', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLHB10', category: 'Kitchen', subCategory: 'Hand Blenders' },
		{ modelNumber: 'LLTF01', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLEF06', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLEF04', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLGS211', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS411', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS311', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS30', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{
			modelNumber: 'LLM252',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{ modelNumber: 'LLDI20', category: 'Home Appliances', subCategory: 'Dry Iron' },
		{ modelNumber: 'LLDI02', category: 'Home Appliances', subCategory: 'Dry Iron' },
		{ modelNumber: 'LLCF403', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF402', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF401', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF303', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF302', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF301', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF203', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF202', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF201', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLMB50', category: 'Home Appliances', subCategory: 'REFRIGERATOR' },
		{ modelNumber: 'LLMB92', category: 'Home Appliances', subCategory: 'REFRIGERATOR' },
		{ modelNumber: 'LLEK20', category: 'Kitchen', subCategory: 'KETTLE' },
		{ modelNumber: 'LLEK10', category: 'Kitchen', subCategory: 'KETTLE' },
		{
			modelNumber: 'LLVST400',
			category: 'Home Appliances',
			subCategory: 'Voltage Stabilizers',
		},
		{ modelNumber: 'LLJMG01', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLGS201', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLM630', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLIC02', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{
			modelNumber: 'LLMUS45',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLMUS72',
			category: 'Health & Personal Care',
			subCategory: 'BODY MASSAGER',
		},
		{
			modelNumber: 'LLMUS63',
			category: 'Health & Personal Care',
			subCategory: 'BODY MASSAGER',
		},
		{
			modelNumber: 'LLMUS54',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLMUS36',
			category: 'Health & Personal Care',
			subCategory: 'BODY MASSAGER',
		},
		{
			modelNumber: 'LLMUS27',
			category: 'Health & Personal Care',
			subCategory: 'BODY MASSAGER',
		},
		{
			modelNumber: 'LLMUS18',
			category: 'Health & Personal Care',
			subCategory: 'BODY MASSAGER',
		},
		{
			modelNumber: 'LLMUS09',
			category: 'Health & Personal Care',
			subCategory: 'BODY MASSAGER',
		},
		{ modelNumber: 'LLAWMD06', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLAWM04', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLAWM03', category: 'Home Appliances', subCategory: 'WASHING MACHINE' },
		{ modelNumber: 'LLIC14', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLIC23', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLCKR61', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR60', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR51', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR50', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR41', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPCM07-1', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLPCM05-1', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLWH108', category: 'Home Appliances', subCategory: 'Water Heater' },
		{ modelNumber: 'LLMG90', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLDI10', category: 'Home Appliances', subCategory: 'Dry Iron' },
		{ modelNumber: 'LLPCM15', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLMG63', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLPC55', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPC61', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPC43', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPC37', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCF76', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF66', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF56', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF136', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLIC06', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLIC21', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLPC60', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPC54', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPC42', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLPC36', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLGS54', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLGS60', category: 'Kitchen', subCategory: 'GAS STOVE' },
		{ modelNumber: 'LLCF124', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF130', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLYM06', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM07', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM08', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM09', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM10', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM11', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLAS01', category: 'SPORTS', subCategory: 'EXERCISE' },
		{ modelNumber: 'LLAR01', category: 'SPORTS', subCategory: 'EXERCISE' },
		{ modelNumber: 'LLYM01', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM02', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM03', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM04', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM05', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM12', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLPCW30', category: 'Lifestyle', subCategory: 'FEMALE GROOMING' },
		{ modelNumber: 'LLDI19', category: 'Home Appliances', subCategory: 'Dry Iron' },
		{ modelNumber: 'LLCMB13', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB07', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB40', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB31', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB30', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB17', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB16', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB12', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB15', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB14', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB11', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB10', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLMG12', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLTM117', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM90', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM108', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM72', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM63', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLTM54', category: 'SPORTS', subCategory: 'TREADMILLS' },
		{ modelNumber: 'LLEK30', category: 'Kitchen', subCategory: 'KETTLE' },
		{ modelNumber: 'LLF81', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLF90', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLCMB70', category: 'Home Appliances', subCategory: 'Combo' },
		{
			modelNumber: 'LLS09',
			category: 'Health & Personal Care',
			subCategory: 'Other Massagers',
		},
		{
			modelNumber: 'LLRH09',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{
			modelNumber: 'LLM279',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
		{ modelNumber: 'LLPCM17', category: 'Lifestyle', subCategory: 'TRIMMERS & SHAVERS' },
		{ modelNumber: 'LLCF502', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCF501', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLM270', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLCKR202', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR201', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR224', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR223', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR222', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR221', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR313', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR212', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR211', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLCKR214', category: 'Kitchen', subCategory: 'COOKWARE' },
		{ modelNumber: 'LLF720', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLSSL01', category: 'Smart Home', subCategory: 'SMART LIGHT' },
		{ modelNumber: 'LLDS06', category: 'Smart Home', subCategory: 'DOOR SENSORS' },
		{ modelNumber: 'LLDS05', category: 'Smart Home', subCategory: 'Smart Misc' },
		{ modelNumber: 'LLDS04', category: 'Smart Home', subCategory: 'Smart Misc' },
		{ modelNumber: 'LLDS03', category: 'Smart Home', subCategory: 'Smart Misc' },
		{ modelNumber: 'LLDS02', category: 'Smart Home', subCategory: 'Smart Misc' },
		{ modelNumber: 'LLDS01', category: 'Smart Home', subCategory: 'Smart Misc' },
		{ modelNumber: 'LLMG755', category: 'Kitchen', subCategory: 'MIXER GRINDER' },
		{ modelNumber: 'LLSBSR505', category: 'Home Appliances', subCategory: 'REFRIGERATOR' },
		{ modelNumber: 'LLCFBL03', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCFBL02', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLCFBL01', category: 'Home Appliances', subCategory: 'Ceiling Fans' },
		{ modelNumber: 'LLF99', category: 'SPORTS', subCategory: 'BIKES' },
		{ modelNumber: 'LLRC15', category: 'Kitchen', subCategory: 'Pressure Cooker' },
		{ modelNumber: 'LLCMB72', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB73', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLCMB71', category: 'Home Appliances', subCategory: 'Combo' },
		{ modelNumber: 'LLIC10', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{ modelNumber: 'LLVC30', category: 'Home Appliances', subCategory: 'Vacuum Cleaner' },
		{ modelNumber: 'LLVC02', category: 'Home Appliances', subCategory: 'Vacuum Cleaner' },
		{ modelNumber: 'LLYM13', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM14', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM15', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM16', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM17', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM18', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM19', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLYM20', category: 'SPORTS', subCategory: 'YOGA MAT' },
		{ modelNumber: 'LLM288', category: 'Health & Personal Care', subCategory: 'BODY MASSAGER' },
		{ modelNumber: 'LLOT14', category: 'Kitchen', subCategory: 'OTG' },
		{ modelNumber: 'LLIC30', category: 'Kitchen', subCategory: 'INDUCTION COOKTOP' },
		{
			modelNumber: 'LLM900',
			category: 'Health & Personal Care',
			subCategory: 'FOOT & LEG MASSAGER',
		},
	],

	raazorpay: {
		API: 'https://api.razorpay.com/v1',
	},
};
module.exports = OPTIONS;
